// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RollMaster.Data;

#nullable disable

namespace RollMaster.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328031120_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RollMaster.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BBLuki")
                        .HasColumnType("int");

                    b.Property<int>("BBMiecze")
                        .HasColumnType("int");

                    b.Property<int>("BBTopory")
                        .HasColumnType("int");

                    b.Property<int>("BBWlocznie")
                        .HasColumnType("int");

                    b.Property<int>("Cien")
                        .HasColumnType("int");

                    b.Property<int>("Czujnosc")
                        .HasColumnType("int");

                    b.Property<string>("Ekwipunek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("HelmNazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HelmObciazenie")
                        .HasColumnType("int");

                    b.Property<int?>("HelmPancerz")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inspiracja")
                        .HasColumnType("int");

                    b.Property<int>("Madrosc")
                        .HasColumnType("int");

                    b.Property<int>("Mestwo")
                        .HasColumnType("int");

                    b.Property<int>("Nadzieja")
                        .HasColumnType("int");

                    b.Property<string>("Nagrody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Obciazenie")
                        .HasColumnType("int");

                    b.Property<int>("ObecnaNadzieja")
                        .HasColumnType("int");

                    b.Property<int>("ObecnaWytrzymalosc")
                        .HasColumnType("int");

                    b.Property<int>("Obrona")
                        .HasColumnType("int");

                    b.Property<int>("PTRozum")
                        .HasColumnType("int");

                    b.Property<int>("PTSerce")
                        .HasColumnType("int");

                    b.Property<int>("PTSila")
                        .HasColumnType("int");

                    b.Property<string>("Patron")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Piesni")
                        .HasColumnType("int");

                    b.Property<int>("PietnoCienia")
                        .HasColumnType("int");

                    b.Property<int>("Polowanie")
                        .HasColumnType("int");

                    b.Property<string>("Powolanie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoziomZycia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Przekonywanie")
                        .HasColumnType("int");

                    b.Property<int>("Przenikliwosc")
                        .HasColumnType("int");

                    b.Property<bool>("Przygnebienie")
                        .HasColumnType("bit");

                    b.Property<string>("Przymioty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Przywary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PunktyPrzygody")
                        .HasColumnType("int");

                    b.Property<int>("PunktyUmiejetnosci")
                        .HasColumnType("int");

                    b.Property<int>("PunktyZazylosci")
                        .HasColumnType("int");

                    b.Property<string>("R1Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("R1Obciazenie")
                        .HasColumnType("int");

                    b.Property<int?>("R1Obrazenia")
                        .HasColumnType("int");

                    b.Property<int?>("R1Przebicie")
                        .HasColumnType("int");

                    b.Property<string>("R1Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R2Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("R2Obciazenie")
                        .HasColumnType("int");

                    b.Property<int?>("R2Obrazenia")
                        .HasColumnType("int");

                    b.Property<int?>("R2Przebicie")
                        .HasColumnType("int");

                    b.Property<string>("R2Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R3Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("R3Obciazenie")
                        .HasColumnType("int");

                    b.Property<int?>("R3Obrazenia")
                        .HasColumnType("int");

                    b.Property<int?>("R3Przebicie")
                        .HasColumnType("int");

                    b.Property<string>("R3Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R4Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("R4Obciazenie")
                        .HasColumnType("int");

                    b.Property<int?>("R4Obrazenia")
                        .HasColumnType("int");

                    b.Property<int?>("R4Przebicie")
                        .HasColumnType("int");

                    b.Property<string>("R4Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rana")
                        .HasColumnType("bit");

                    b.Property<int>("Rekonesans")
                        .HasColumnType("int");

                    b.Property<int>("Respekt")
                        .HasColumnType("int");

                    b.Property<string>("RodzimaKultura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rzemioslo")
                        .HasColumnType("int");

                    b.Property<string>("SciezkaCienia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Skarb")
                        .HasColumnType("int");

                    b.Property<int>("Skradanie")
                        .HasColumnType("int");

                    b.Property<string>("StopienRany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SzczegolnaSympatia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Szukanie")
                        .HasColumnType("int");

                    b.Property<string>("TarczaNazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TarczaObciazenie")
                        .HasColumnType("int");

                    b.Property<int?>("TarczaObrona")
                        .HasColumnType("int");

                    b.Property<int>("Uprzejmosc")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Uzdrawianie")
                        .HasColumnType("int");

                    b.Property<bool>("WCzujnosc")
                        .HasColumnType("bit");

                    b.Property<bool>("WInspiracja")
                        .HasColumnType("bit");

                    b.Property<bool>("WPiesni")
                        .HasColumnType("bit");

                    b.Property<bool>("WPolowanie")
                        .HasColumnType("bit");

                    b.Property<bool>("WPrzekonywanie")
                        .HasColumnType("bit");

                    b.Property<bool>("WPrzenikliwosc")
                        .HasColumnType("bit");

                    b.Property<bool>("WRekonesans")
                        .HasColumnType("bit");

                    b.Property<bool>("WRespekt")
                        .HasColumnType("bit");

                    b.Property<bool>("WRzemioslo")
                        .HasColumnType("bit");

                    b.Property<bool>("WSkradanie")
                        .HasColumnType("bit");

                    b.Property<bool>("WSzukanie")
                        .HasColumnType("bit");

                    b.Property<bool>("WUprzejmosc")
                        .HasColumnType("bit");

                    b.Property<bool>("WUzdrawianie")
                        .HasColumnType("bit");

                    b.Property<bool>("WWedrowka")
                        .HasColumnType("bit");

                    b.Property<bool>("WWiedza")
                        .HasColumnType("bit");

                    b.Property<bool>("WWojaczka")
                        .HasColumnType("bit");

                    b.Property<bool>("WZagadki")
                        .HasColumnType("bit");

                    b.Property<bool>("WZwinnosc")
                        .HasColumnType("bit");

                    b.Property<int>("WartoscRozum")
                        .HasColumnType("int");

                    b.Property<int>("WartoscSerce")
                        .HasColumnType("int");

                    b.Property<int>("WartoscSila")
                        .HasColumnType("int");

                    b.Property<int>("Wedrowka")
                        .HasColumnType("int");

                    b.Property<int>("Wiedza")
                        .HasColumnType("int");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<int>("Wojaczka")
                        .HasColumnType("int");

                    b.Property<bool>("Wyczerpanie")
                        .HasColumnType("bit");

                    b.Property<string>("Wyrozniki")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wytrzymalosc")
                        .HasColumnType("int");

                    b.Property<int>("Zagadki")
                        .HasColumnType("int");

                    b.Property<string>("ZbrojaNazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZbrojaObciazenie")
                        .HasColumnType("int");

                    b.Property<int?>("ZbrojaPancerz")
                        .HasColumnType("int");

                    b.Property<int>("Znuzenie")
                        .HasColumnType("int");

                    b.Property<int>("Zwinnosc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("RollMaster.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("RollMaster.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RollMaster.Models.Character", b =>
                {
                    b.HasOne("RollMaster.Models.Game", "Game")
                        .WithMany("Characters")
                        .HasForeignKey("GameId");

                    b.HasOne("RollMaster.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RollMaster.Models.Game", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
